
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Landing from "./landing";





export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>We Learn</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Landing />
   

			<footer className={styles.footer}>
				Proudly brought to you by
				
				<span className={styles.logo}>
					<Image
						src="/welearn.jpg"
						width={200}
						height={150}
					/>
				</span>
			</footer>
		</div>
	);
}


